name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          VERSION="${VERSION#v}"

          IFS='.' read -r major minor patch <<< "$VERSION"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t "ghcr.io/toomanyfiles/traefik-relay:v${VERSION}" \
            -t "ghcr.io/toomanyfiles/traefik-relay:v${major}" \
            -t "ghcr.io/toomanyfiles/traefik-relay:v${major}.${minor}" \
            -t "ghcr.io/toomanyfiles/traefik-relay:latest" \
            .
